environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor.bat'

deploy: off

after_build:
#  - 7z a YAXF_debug.zip .\debug\*
  - 7z a YAXF_release.zip .\release\*

artifacts:
#  - path: YAXF_debug.zip
  - path: YAXF_release.zip
